region = "{{ .stack.region }}"
alert_manager_record_name = "{{ .kapp.vars.alert_manager_hostname }}"
grafana_record_name = "{{ .kapp.vars.grafana_hostname }}"
prometheus_dns_record_name = "{{ .kapp.vars.prometheus_hostname }}"
cname_hostname = " {{ .kapp.vars.cname_hostname }}"
hosted_zone = "{{ .kapp.vars.hosted_zone }}"
